/**
 * Installer + doctor lifecycle across the three harnesses (Claude Code,
 * OpenCode, Codex).
 *
 * Every test builds its own fixture in a temp dir. Nothing here reads the
 * repo's `.agents/compatibility/command-aliases.json`, its wrappers or its
 * skills, because those are regenerated by other tooling and would make the
 * suite flap. The hook adapters and MCP configs ARE copied from the repo:
 * they are the committed contract the engine validates, not generated output.
 */

import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

import { afterEach, describe, expect, test } from 'bun:test';

import { diagnoseAgentCompatibility } from './doctor.ts';
import {
  buildCommunitySkillArgs,
  describeAgentDetection,
  detectAgents,
  discoverRequiredEnvVars,
  launchCommandsForAgents,
  migrateAgentIds,
  parseAgentsEnv,
  PROJECT_SKILL_DESTINATION,
  repairRepositoryCompatibility,
} from './install.ts';
import { declaredMcpIds } from './lib/agent-compatibility-contracts.ts';
import { CLAUDE_INSTRUCTIONS_SHIM, claudeSkillsAliasPlan, repairClaudeSkillsAlias } from './lib/agent-compatibility.ts';

const REPO_ROOT = resolve(import.meta.dir, '..');
const temporaryRoots: string[] = [];

function temporaryRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'agent-lifecycle-'));
  temporaryRoots.push(root);
  return root;
}

function write(root: string, relativePath: string, content: string): void {
  const destination = join(root, relativePath);
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, content);
}

function copyFromRepo(root: string, relativePath: string): void {
  const destination = join(root, relativePath);
  mkdirSync(dirname(destination), { recursive: true });
  cpSync(join(REPO_ROOT, relativePath), destination, { recursive: true });
}

const FIXTURE_ALIASES = [
  { alias: 'dev-roadmap', skill: 'project-context', mode: 'dev-roadmap' },
  { alias: 'business-data-map', skill: 'project-context', mode: 'business-data-map' },
] as const;

/**
 * A repo that satisfies the whole contract EXCEPT the generated artifacts
 * (`.claude/skills` alias, command wrappers), which `repairRepositoryCompatibility`
 * is expected to create.
 */
function compatibilityFixture(): string {
  const root = temporaryRoot();
  write(root, 'AGENTS.md', '# AGENTS.md\n\nCanonical instructions.\n');
  write(root, 'CLAUDE.md', CLAUDE_INSTRUCTIONS_SHIM);
  write(root, '.agents/compatibility/command-aliases.json', `${JSON.stringify({
    version: 1,
    wrapperHosts: ['claude', 'opencode'],
    aliases: FIXTURE_ALIASES.map(alias => ({
      ...alias,
      description: `Run ${alias.mode}`,
      argumentHint: '[args]',
      forwardArguments: true,
      mutability: 'local-write',
    })),
  }, null, 2)}\n`);
  write(
    root,
    '.agents/skills/project-context/SKILL.md',
    `---\nname: project-context\n---\n\nModes: ${FIXTURE_ALIASES.map(alias => `\`${alias.mode}\``).join(', ')}.\n`,
  );
  for (const path of [
    '.agents/hooks/personality-reinject.mjs',
    '.claude/settings.json',
    '.opencode/plugins/personality-reinject.js',
    '.codex/hooks.json',
    '.codex/config.toml',
    '.mcp.json',
    'opencode.jsonc',
  ]) { copyFromRepo(root, path); }
  return root;
}

afterEach(() => {
  while (temporaryRoots.length > 0) {
    const root = temporaryRoots.pop();
    if (root) { rmSync(root, { recursive: true, force: true }); }
  }
});

describe('installer harness detection', () => {
  test('parses INSTALL_AGENTS for the three ids, drops unknowns and duplicates', () => {
    expect(parseAgentsEnv('codex,claude-code,codex,unknown,opencode')).toEqual([
      'codex',
      'claude-code',
      'opencode',
    ]);
    expect(parseAgentsEnv('')).toBeNull();
    expect(parseAgentsEnv(undefined)).toBeNull();
    expect(parseAgentsEnv('nothing-valid')).toEqual([]);
    expect(migrateAgentIds(['claude-code', 'opencode'])).toEqual(['claude-code', 'opencode']);
    expect(migrateAgentIds(['codex', 'unknown', 'codex'])).toEqual(['codex']);
    expect(migrateAgentIds('codex')).toEqual([]);
  });

  test('detects Claude Code and OpenCode from their home config directories', async () => {
    const root = temporaryRoot();
    const home = join(root, 'home');
    mkdirSync(join(home, '.claude'), { recursive: true });
    mkdirSync(join(home, '.config', 'opencode'), { recursive: true });

    const detected = await detectAgents({ home, root, binaryExists: () => false });
    expect(detected).toEqual({
      claudeCode: true,
      opencode: true,
      codexCli: false,
      codexConfigured: false,
    });
  });

  test('distinguishes the Codex CLI from a Desktop-only repository configuration', async () => {
    const root = temporaryRoot();
    write(root, '.codex/config.toml', '[shell_environment_policy]\ninherit = "core"\n');

    const cliAndConfig = await detectAgents({ home: join(root, 'home'), root, binaryExists: binary => binary === 'codex' });
    expect(cliAndConfig).toEqual({ claudeCode: false, opencode: false, codexCli: true, codexConfigured: true });
    expect(describeAgentDetection(cliAndConfig)).toContain('Codex: CLI found');

    const configOnly = await detectAgents({ home: join(root, 'home'), root, binaryExists: () => false });
    expect(configOnly).toMatchObject({ codexCli: false, codexConfigured: true });
    expect(describeAgentDetection(configOnly)).toContain('repository configured for Desktop');

    const nothing = await detectAgents({ home: join(root, 'home'), root: join(root, 'empty'), binaryExists: () => false });
    expect(nothing).toEqual({ claudeCode: false, opencode: false, codexCli: false, codexConfigured: false });
    expect(describeAgentDetection(nothing)).toContain('Codex: not found');
  });

  test('falls back to the PATH lookup when no home config directory exists', async () => {
    // The PATH probe is injectable (`binaryExists`) because Bun's spawnSync does
    // not reliably observe a mutated `process.env.PATH`; the branch under test is
    // "directory absent -> executable decides", which this exercises exactly.
    const root = temporaryRoot();
    const probed: string[] = [];
    const detected = await detectAgents({
      home: join(root, 'home'),
      root,
      binaryExists: (binary) => {
        probed.push(binary);
        return binary === 'claude' || binary === 'codex';
      },
    });
    expect(probed.sort()).toEqual(['claude', 'codex', 'opencode']);
    expect(detected).toEqual({ claudeCode: true, opencode: false, codexCli: true, codexConfigured: false });
  });
});

describe('installer skill and env contracts', () => {
  test('keeps project skills in the canonical store and maps global skills to every harness', () => {
    const item = { package: 'owner/repo', skill: 'example' };
    expect(PROJECT_SKILL_DESTINATION).toBe('.agents/skills');
    expect(buildCommunitySkillArgs(item, 'project', ['claude-code', 'opencode', 'codex']))
      .toEqual(['skills', 'add', 'owner/repo', '--skill', 'example', '--yes']);
    expect(buildCommunitySkillArgs({ package: 'owner/all', skill: '*' }, 'project', ['codex']))
      .toEqual(['skills', 'add', 'owner/all', '--yes']);
    expect(buildCommunitySkillArgs(item, 'global', ['claude-code', 'opencode', 'codex']))
      .toEqual([
        'skills',
        'add',
        'owner/repo',
        '--skill',
        'example',
        '--global',
        '--agent',
        'claude-code',
        '--agent',
        'opencode',
        '--agent',
        'codex',
        '--yes',
      ]);
  });

  test('discovers the env-var union across the selected harnesses', async () => {
    const root = temporaryRoot();
    // Claude Code placeholders are literal `${VAR}` text in .mcp.json by design.
    // eslint-disable-next-line no-template-curly-in-string
    const claudePlaceholders = { CLAUDE_ONLY_KEY: '${CLAUDE_ONLY_KEY}', SHARED_TOKEN: '${SHARED_TOKEN:-x}' };
    write(root, '.mcp.json', JSON.stringify({ mcpServers: { a: { env: claudePlaceholders } } }));
    write(root, 'opencode.jsonc', '{\n  // comment\n  "mcp": { "a": { "environment": { "SHARED_TOKEN": "{env:SHARED_TOKEN}", "OPENCODE_ONLY_KEY": "{env:OPENCODE_ONLY_KEY}" } } }\n}\n');
    write(root, '.codex/config.toml', [
      '[mcp_servers.tavily]',
      'url = "https://example.invalid/mcp"',
      'bearer_token_env_var = "SHARED_TOKEN"',
      '',
      '[mcp_servers.supabase]',
      'command = "bunx"',
      'env_vars = ["CODEX_ONLY_KEY", "SHARED_TOKEN"]',
      '',
      '[mcp_servers.supabase.env]',
      'LOG_LEVEL = "error"',
      'NOT_A_SECRET = "literal"',
      '',
    ].join('\n'));

    expect(await discoverRequiredEnvVars(['codex'], root)).toEqual(['CODEX_ONLY_KEY', 'SHARED_TOKEN']);
    expect(await discoverRequiredEnvVars(['claude-code'], root)).toEqual(['CLAUDE_ONLY_KEY', 'SHARED_TOKEN']);
    expect(await discoverRequiredEnvVars(['claude-code', 'opencode', 'codex'], root)).toEqual([
      'CLAUDE_ONLY_KEY',
      'CODEX_ONLY_KEY',
      'OPENCODE_ONLY_KEY',
      'SHARED_TOKEN',
    ]);
    expect(await discoverRequiredEnvVars([], root)).toEqual([]);
  });

  test('exposes one launch wrapper per harness', () => {
    expect(launchCommandsForAgents(['claude-code', 'opencode', 'codex']))
      .toEqual(['bun run claude', 'bun run opencode', 'bun run codex']);
  });
});

describe('compatibility repair lifecycle', () => {
  test('constructs portable POSIX and Windows alias plans', () => {
    const root = temporaryRoot();
    expect(claudeSkillsAliasPlan(root, 'linux')).toMatchObject({ target: '../.agents/skills', type: 'symlink' });
    expect(claudeSkillsAliasPlan(root, 'win32')).toMatchObject({ target: join(root, '.agents', 'skills'), type: 'junction' });
  });

  test('creates the alias and both wrapper sets, then is a no-op on the second run', () => {
    const root = compatibilityFixture();
    const first = repairRepositoryCompatibility(root, 'linux');
    expect(first.alias.status).toBe('created');
    expect(first.wrappersWritten).toBe(FIXTURE_ALIASES.length * 2);
    for (const alias of FIXTURE_ALIASES) {
      const claude = readFileSync(join(root, '.claude/commands', `${alias.alias}.md`), 'utf8');
      const opencode = readFileSync(join(root, '.opencode/commands', `${alias.alias}.md`), 'utf8');
      expect(claude).toBe(opencode);
      expect(claude).toContain(`Invoke skill \`${alias.skill}\` in mode \`${alias.mode}\`.`);
    }
    // The alias makes the canonical skill visible where Claude Code looks.
    expect(readFileSync(join(root, '.claude/skills/project-context/SKILL.md'), 'utf8')).toContain('name: project-context');

    const second = repairRepositoryCompatibility(root, 'linux');
    expect(second).toMatchObject({ wrappersWritten: 0, alias: { status: 'valid' } });
  });

  test('reclaims the skills CLI per-skill symlink shim without losing a skill body', () => {
    const root = compatibilityFixture();
    mkdirSync(join(root, '.claude/skills'), { recursive: true });
    symlinkSync('../../.agents/skills/project-context', join(root, '.claude/skills/project-context'), 'dir');

    expect(repairRepositoryCompatibility(root, 'linux').alias.status).toBe('repaired');
    expect(readFileSync(join(root, '.agents/skills/project-context/SKILL.md'), 'utf8')).toContain('name: project-context');
    expect(readFileSync(join(root, '.claude/skills/project-context/SKILL.md'), 'utf8')).toContain('name: project-context');
  });

  test('refuses to replace a real Claude skills directory and keeps its content', () => {
    const root = compatibilityFixture();
    mkdirSync(join(root, '.claude/skills'), { recursive: true });
    writeFileSync(join(root, '.claude/skills/owned.txt'), 'preserve me\n');

    expect(() => repairClaudeSkillsAlias(root, 'linux')).toThrow('Refusing to replace');
    expect(() => repairRepositoryCompatibility(root, 'linux')).toThrow('Refusing to replace');
    expect(readFileSync(join(root, '.claude/skills/owned.txt'), 'utf8')).toBe('preserve me\n');
  });

  test('surfaces contract errors the repair cannot fix', () => {
    const root = compatibilityFixture();
    rmSync(join(root, '.codex/hooks.json'));

    expect(() => repairRepositoryCompatibility(root, 'linux')).toThrow('Hook compatibility file missing: .codex/hooks.json');
  });
});

describe('doctor diagnosis', () => {
  test('reports a compliant fixture as file-correct, with trust as unverifiable runtime state', () => {
    const root = compatibilityFixture();
    repairRepositoryCompatibility(root, 'linux');
    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false });

    expect(diagnostic.file_correct).toBe(true);
    expect(diagnostic.errors).toEqual([]);
    expect(diagnostic.instructions).toEqual({ agents_md: true, claude_shim: true, canonical_skills: true, claude_alias: true });
    expect(diagnostic.command_wrappers).toEqual({
      expected: FIXTURE_ALIASES.length,
      claude: FIXTURE_ALIASES.length,
      opencode: FIXTURE_ALIASES.length,
      ok: true,
    });
    expect(diagnostic.hooks).toEqual({ claude: true, opencode: true, codex: true, ok: true });
    expect(diagnostic.mcp).toEqual({
      expected_servers: declaredMcpIds(root).length,
      claude: true,
      opencode: true,
      codex: true,
      parity: true,
    });
    expect(diagnostic.codex).toEqual({
      config_exists: true,
      cli_detected: false,
      repository_configured: true,
      desktop_uses_repository_config: true,
      trust_required: true,
      trust_status: 'required-not-verifiable',
    });
  });

  test('flags a CLAUDE.md that is not the exact shim', () => {
    const root = compatibilityFixture();
    repairRepositoryCompatibility(root, 'linux');
    writeFileSync(join(root, 'CLAUDE.md'), '# Real instructions\n\nNot a shim.\n');

    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: true });
    expect(diagnostic.file_correct).toBe(false);
    expect(diagnostic.instructions.claude_shim).toBe(false);
    expect(diagnostic.instructions.agents_md).toBe(true);
    expect(diagnostic.errors.some(error => error.includes('CLAUDE.md must contain exactly'))).toBe(true);
    expect(diagnostic.codex.cli_detected).toBe(true);
  });

  test('flags a hand-edited wrapper while the counts still look complete', () => {
    const root = compatibilityFixture();
    repairRepositoryCompatibility(root, 'linux');
    const wrapper = join(root, '.opencode/commands', `${FIXTURE_ALIASES[0].alias}.md`);
    writeFileSync(wrapper, `${readFileSync(wrapper, 'utf8')}\nExtra prose someone typed by hand.\n`);

    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false });
    expect(diagnostic.command_wrappers.ok).toBe(true);
    expect(diagnostic.file_correct).toBe(false);
    expect(diagnostic.errors).toContainEqual(expect.stringContaining(`opencode command wrapper is stale: .opencode/commands/${FIXTURE_ALIASES[0].alias}.md`));

    // Repair rewrites exactly that wrapper and the diagnosis is clean again.
    expect(repairRepositoryCompatibility(root, 'linux').wrappersWritten).toBe(1);
    expect(diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false }).file_correct).toBe(true);
  });

  test('reports a missing alias and missing Codex config without throwing', () => {
    const root = compatibilityFixture();
    rmSync(join(root, '.codex'), { recursive: true, force: true });

    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false });
    expect(diagnostic.file_correct).toBe(false);
    expect(diagnostic.instructions.claude_alias).toBe(false);
    expect(diagnostic.command_wrappers.ok).toBe(false);
    expect(diagnostic.hooks.codex).toBe(false);
    expect(diagnostic.mcp.codex).toBe(false);
    expect(diagnostic.codex).toMatchObject({ config_exists: false, repository_configured: false });
  });
});
