// Generated by `mcp__claude_ai_Supabase__generate_typescript_types` against
// project fmbpikzpkafptqximhxn. Do not edit by hand — regenerate after any
// migration applied to the Bunkai Supabase project, then `bun run lint:fix`
// to apply the codebase's antfu/ESLint style conventions.

export type Json
  = | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export interface Database {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      acceptance_criteria: {
        Row: {
          created_at: string
          description: string | null
          id: string
          position: number
          title: string
          user_story_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          position?: number
          title: string
          user_story_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          position?: number
          title?: string
          user_story_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'acceptance_criteria_user_story_id_fkey'
            columns: ['user_story_id']
            isOneToOne: false
            referencedRelation: 'user_stories'
            referencedColumns: ['id']
          },
        ]
      }
      access_tokens: {
        Row: {
          created_at: string
          expires_at: string | null
          hash: string
          id: string
          last_used_at: string | null
          name: string | null
          revoked_at: string | null
          scopes: string[]
          token_prefix: string
          user_id: string
          workspace_id: string | null
        }
        Insert: {
          created_at?: string
          expires_at?: string | null
          hash: string
          id?: string
          last_used_at?: string | null
          name?: string | null
          revoked_at?: string | null
          scopes: string[]
          token_prefix: string
          user_id: string
          workspace_id?: string | null
        }
        Update: {
          created_at?: string
          expires_at?: string | null
          hash?: string
          id?: string
          last_used_at?: string | null
          name?: string | null
          revoked_at?: string | null
          scopes?: string[]
          token_prefix?: string
          user_id?: string
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'access_tokens_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      atc_acceptance_criteria: {
        Row: {
          acceptance_criterion_id: string
          atc_id: string
        }
        Insert: {
          acceptance_criterion_id: string
          atc_id: string
        }
        Update: {
          acceptance_criterion_id?: string
          atc_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'atc_acceptance_criteria_acceptance_criterion_id_fkey'
            columns: ['acceptance_criterion_id']
            isOneToOne: false
            referencedRelation: 'acceptance_criteria'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'atc_acceptance_criteria_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
        ]
      }
      atc_assertions: {
        Row: {
          atc_id: string
          content: string
          id: string
          position: number
        }
        Insert: {
          atc_id: string
          content: string
          id?: string
          position?: number
        }
        Update: {
          atc_id?: string
          content?: string
          id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: 'atc_assertions_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
        ]
      }
      atc_steps: {
        Row: {
          atc_id: string
          content: string
          expected: string | null
          id: string
          input_data: string | null
          position: number
        }
        Insert: {
          atc_id: string
          content: string
          expected?: string | null
          id?: string
          input_data?: string | null
          position?: number
        }
        Update: {
          atc_id?: string
          content?: string
          expected?: string | null
          id?: string
          input_data?: string | null
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: 'atc_steps_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
        ]
      }
      atcs: {
        Row: {
          created_at: string
          id: string
          layer: string
          module_id: string
          project_id: string
          slug: string
          status: string
          tags: string[]
          title: string
          tsv: unknown
          updated_at: string
          user_story_id: string
          version: number
        }
        Insert: {
          created_at?: string
          id?: string
          layer: string
          module_id: string
          project_id: string
          slug: string
          status?: string
          tags?: string[]
          title: string
          tsv?: unknown
          updated_at?: string
          user_story_id: string
          version?: number
        }
        Update: {
          created_at?: string
          id?: string
          layer?: string
          module_id?: string
          project_id?: string
          slug?: string
          status?: string
          tags?: string[]
          title?: string
          tsv?: unknown
          updated_at?: string
          user_story_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: 'atcs_module_id_fkey'
            columns: ['module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'atcs_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'atcs_user_story_id_fkey'
            columns: ['user_story_id']
            isOneToOne: false
            referencedRelation: 'user_stories'
            referencedColumns: ['id']
          },
        ]
      }
      modules: {
        Row: {
          created_at: string
          id: string
          name: string
          parent_module_id: string | null
          path: string
          position: number
          project_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          parent_module_id?: string | null
          path: string
          position?: number
          project_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          parent_module_id?: string | null
          path?: string
          position?: number
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'modules_parent_module_id_fkey'
            columns: ['parent_module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'modules_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      projects: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          slug: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          slug: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          slug?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'projects_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      user_stories: {
        Row: {
          created_at: string
          description: string | null
          external_id: string | null
          external_url: string | null
          id: string
          module_id: string
          title: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          external_id?: string | null
          external_url?: string | null
          id?: string
          module_id: string
          title: string
        }
        Update: {
          created_at?: string
          description?: string | null
          external_id?: string | null
          external_url?: string | null
          id?: string
          module_id?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: 'user_stories_module_id_fkey'
            columns: ['module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
        ]
      }
      workspace_members: {
        Row: {
          joined_at: string
          role: string
          status: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          joined_at?: string
          role?: string
          status?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          joined_at?: string
          role?: string
          status?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'workspace_members_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      workspaces: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_user_id: string
          plan: string
          slug: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          owner_user_id: string
          plan?: string
          slug: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_user_id?: string
          plan?: string
          slug?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      bunkai_bootstrap_workspace: {
        Args: { p_name: string, p_slug: string }
        Returns: string
      }
      bunkai_can_write_workspace: { Args: { ws_id: string }, Returns: boolean }
      bunkai_is_workspace_admin: { Args: { ws_id: string }, Returns: boolean }
      bunkai_is_workspace_member: { Args: { ws_id: string }, Returns: boolean }
      bunkai_is_workspace_owner: { Args: { ws_id: string }, Returns: boolean }
      bunkai_save_atc: {
        Args: {
          p_ac_ids: string[]
          p_assertions: Json
          p_atc_id: string
          p_layer: string
          p_steps: Json
          p_tags: string[]
          p_title: string
          p_user_story_id: string
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
  | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
      & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
      ? R
      : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables']
    & DefaultSchema['Views'])
    ? (DefaultSchema['Tables']
      & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
        ? R
        : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema['Tables']
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
    Insert: infer I
  }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema['Tables']
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
    Update: infer U
  }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
  | keyof DefaultSchema['Enums']
  | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
  | keyof DefaultSchema['CompositeTypes']
  | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
