// Generated by `mcp__claude_ai_Supabase__generate_typescript_types` against
// project fmbpikzpkafptqximhxn. Do not edit by hand — regenerate after any
// migration applied to the Bunkai Supabase project, then `bun run lint:fix`
// to apply the codebase's antfu/ESLint style conventions.

export type Json
  = | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export interface Database {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      acceptance_criteria: {
        Row: {
          archived_at: string | null
          created_at: string
          description: string | null
          id: string
          position: number
          title: string
          user_story_id: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          position?: number
          title: string
          user_story_id: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          position?: number
          title?: string
          user_story_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'acceptance_criteria_user_story_id_fkey'
            columns: ['user_story_id']
            isOneToOne: false
            referencedRelation: 'user_stories'
            referencedColumns: ['id']
          },
        ]
      }
      access_token_secrets: {
        Row: {
          hash: string
          token_id: string
        }
        Insert: {
          hash: string
          token_id: string
        }
        Update: {
          hash?: string
          token_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'access_token_secrets_token_id_fkey'
            columns: ['token_id']
            isOneToOne: true
            referencedRelation: 'access_tokens'
            referencedColumns: ['id']
          },
        ]
      }
      access_tokens: {
        Row: {
          created_at: string
          expires_at: string | null
          id: string
          last_used_at: string | null
          name: string | null
          revoked_at: string | null
          scopes: string[]
          token_prefix: string
          user_id: string
          workspace_id: string | null
        }
        Insert: {
          created_at?: string
          expires_at?: string | null
          id?: string
          last_used_at?: string | null
          name?: string | null
          revoked_at?: string | null
          scopes: string[]
          token_prefix: string
          user_id: string
          workspace_id?: string | null
        }
        Update: {
          created_at?: string
          expires_at?: string | null
          id?: string
          last_used_at?: string | null
          name?: string | null
          revoked_at?: string | null
          scopes?: string[]
          token_prefix?: string
          user_id?: string
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'access_tokens_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      activity_log: {
        Row: {
          action: string
          actor_user_id: string | null
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          payload: Json
          workspace_id: string | null
        }
        Insert: {
          action: string
          actor_user_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          payload?: Json
          workspace_id?: string | null
        }
        Update: {
          action?: string
          actor_user_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          payload?: Json
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'activity_log_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      atc_acceptance_criteria: {
        Row: {
          acceptance_criterion_id: string
          atc_id: string
        }
        Insert: {
          acceptance_criterion_id: string
          atc_id: string
        }
        Update: {
          acceptance_criterion_id?: string
          atc_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'atc_acceptance_criteria_acceptance_criterion_id_fkey'
            columns: ['acceptance_criterion_id']
            isOneToOne: false
            referencedRelation: 'acceptance_criteria'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'atc_acceptance_criteria_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
        ]
      }
      atc_assertions: {
        Row: {
          atc_id: string
          content: string
          id: string
          position: number
        }
        Insert: {
          atc_id: string
          content: string
          id?: string
          position?: number
        }
        Update: {
          atc_id?: string
          content?: string
          id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: 'atc_assertions_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
        ]
      }
      atc_steps: {
        Row: {
          atc_id: string
          content: string
          expected: string | null
          id: string
          input_data: string | null
          position: number
        }
        Insert: {
          atc_id: string
          content: string
          expected?: string | null
          id?: string
          input_data?: string | null
          position?: number
        }
        Update: {
          atc_id?: string
          content?: string
          expected?: string | null
          id?: string
          input_data?: string | null
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: 'atc_steps_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
        ]
      }
      atcs: {
        Row: {
          archived_at: string | null
          created_at: string
          id: string
          layer: string
          module_id: string
          project_id: string
          slug: string
          status: string
          tags: string[]
          title: string
          tsv: unknown
          updated_at: string
          user_story_id: string
          version: number
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          id?: string
          layer: string
          module_id: string
          project_id: string
          slug: string
          status?: string
          tags?: string[]
          title: string
          tsv?: unknown
          updated_at?: string
          user_story_id: string
          version?: number
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          id?: string
          layer?: string
          module_id?: string
          project_id?: string
          slug?: string
          status?: string
          tags?: string[]
          title?: string
          tsv?: unknown
          updated_at?: string
          user_story_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: 'atcs_module_id_fkey'
            columns: ['module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'atcs_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'atcs_user_story_id_fkey'
            columns: ['user_story_id']
            isOneToOne: false
            referencedRelation: 'user_stories'
            referencedColumns: ['id']
          },
        ]
      }
      bugs: {
        Row: {
          atc_id: string | null
          created_at: string
          created_by: string | null
          description: string | null
          evidence_urls: string[]
          id: string
          module_id: string
          project_id: string
          run_id: string | null
          run_step_id: string | null
          severity: string
          status: string
          steps_to_reproduce: string
          title: string
          updated_at: string
          workspace_id: string
        }
        Insert: {
          atc_id?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          evidence_urls?: string[]
          id?: string
          module_id: string
          project_id: string
          run_id?: string | null
          run_step_id?: string | null
          severity: string
          status?: string
          steps_to_reproduce?: string
          title: string
          updated_at?: string
          workspace_id: string
        }
        Update: {
          atc_id?: string | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          evidence_urls?: string[]
          id?: string
          module_id?: string
          project_id?: string
          run_id?: string | null
          run_step_id?: string | null
          severity?: string
          status?: string
          steps_to_reproduce?: string
          title?: string
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'bugs_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bugs_module_id_fkey'
            columns: ['module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bugs_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bugs_run_id_fkey'
            columns: ['run_id']
            isOneToOne: false
            referencedRelation: 'runs'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bugs_run_step_id_fkey'
            columns: ['run_step_id']
            isOneToOne: false
            referencedRelation: 'run_steps'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bugs_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      feature_flags: {
        Row: {
          created_at: string
          enabled: boolean
          id: string
          key: string
          payload: Json
          scope: string
          updated_at: string
          workspace_id: string | null
        }
        Insert: {
          created_at?: string
          enabled?: boolean
          id?: string
          key: string
          payload?: Json
          scope?: string
          updated_at?: string
          workspace_id?: string | null
        }
        Update: {
          created_at?: string
          enabled?: boolean
          id?: string
          key?: string
          payload?: Json
          scope?: string
          updated_at?: string
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'feature_flags_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      idempotency_keys: {
        Row: {
          created_at: string
          endpoint: string
          expires_at: string
          id: string
          key: string
          request_hash: string
          response_snapshot: Json | null
          response_status: number | null
          status: string
          user_id: string
          workspace_id: string | null
        }
        Insert: {
          created_at?: string
          endpoint: string
          expires_at?: string
          id?: string
          key: string
          request_hash: string
          response_snapshot?: Json | null
          response_status?: number | null
          status?: string
          user_id: string
          workspace_id?: string | null
        }
        Update: {
          created_at?: string
          endpoint?: string
          expires_at?: string
          id?: string
          key?: string
          request_hash?: string
          response_snapshot?: Json | null
          response_status?: number | null
          status?: string
          user_id?: string
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'idempotency_keys_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      import_jobs: {
        Row: {
          completed_at: string | null
          created_at: string
          created_count: number
          errors: Json
          id: string
          imported_count: number
          jql: string
          next_page_token: string | null
          project_id: string
          skipped_count: number
          started_at: string | null
          status: string
          updated_count: number
          workspace_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          created_count?: number
          errors?: Json
          id?: string
          imported_count?: number
          jql: string
          next_page_token?: string | null
          project_id: string
          skipped_count?: number
          started_at?: string | null
          status?: string
          updated_count?: number
          workspace_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          created_count?: number
          errors?: Json
          id?: string
          imported_count?: number
          jql?: string
          next_page_token?: string | null
          project_id?: string
          skipped_count?: number
          started_at?: string | null
          status?: string
          updated_count?: number
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'import_jobs_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'import_jobs_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      magic_link_token_secrets: {
        Row: {
          ip_hash: string | null
          magic_link_token_id: string
          token_hash: string
        }
        Insert: {
          ip_hash?: string | null
          magic_link_token_id: string
          token_hash: string
        }
        Update: {
          ip_hash?: string | null
          magic_link_token_id?: string
          token_hash?: string
        }
        Relationships: [
          {
            foreignKeyName: 'magic_link_token_secrets_magic_link_token_id_fkey'
            columns: ['magic_link_token_id']
            isOneToOne: true
            referencedRelation: 'magic_link_tokens'
            referencedColumns: ['id']
          },
        ]
      }
      magic_link_tokens: {
        Row: {
          consumed_at: string | null
          email: string
          expires_at: string
          id: string
          issued_at: string
          user_agent: string | null
        }
        Insert: {
          consumed_at?: string | null
          email: string
          expires_at?: string
          id?: string
          issued_at?: string
          user_agent?: string | null
        }
        Update: {
          consumed_at?: string | null
          email?: string
          expires_at?: string
          id?: string
          issued_at?: string
          user_agent?: string | null
        }
        Relationships: []
      }
      modules: {
        Row: {
          archived_at: string | null
          created_at: string
          description: string | null
          id: string
          name: string
          parent_module_id: string | null
          path: string
          position: number
          project_id: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name: string
          parent_module_id?: string | null
          path: string
          position?: number
          project_id: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          parent_module_id?: string | null
          path?: string
          position?: number
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'modules_parent_module_id_fkey'
            columns: ['parent_module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'modules_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      project_environments: {
        Row: {
          created_at: string
          id: string
          name: string
          project_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          project_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          project_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_environments_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      projects: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          slug: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          slug: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          slug?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'projects_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      run_atcs: {
        Row: {
          atc_id: string | null
          atc_title: string
          id: string
          position: number
          run_id: string
          status: string
        }
        Insert: {
          atc_id?: string | null
          atc_title: string
          id?: string
          position: number
          run_id: string
          status?: string
        }
        Update: {
          atc_id?: string | null
          atc_title?: string
          id?: string
          position?: number
          run_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: 'run_atcs_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'run_atcs_run_id_fkey'
            columns: ['run_id']
            isOneToOne: false
            referencedRelation: 'runs'
            referencedColumns: ['id']
          },
        ]
      }
      run_steps: {
        Row: {
          atc_step_id: string | null
          content: string
          evidence_url: string | null
          executed_at: string | null
          expected: string | null
          id: string
          input_data: string | null
          note: string | null
          position: number
          run_atc_id: string
          status: string
        }
        Insert: {
          atc_step_id?: string | null
          content: string
          evidence_url?: string | null
          executed_at?: string | null
          expected?: string | null
          id?: string
          input_data?: string | null
          note?: string | null
          position: number
          run_atc_id: string
          status?: string
        }
        Update: {
          atc_step_id?: string | null
          content?: string
          evidence_url?: string | null
          executed_at?: string | null
          expected?: string | null
          id?: string
          input_data?: string | null
          note?: string | null
          position?: number
          run_atc_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: 'run_steps_atc_step_id_fkey'
            columns: ['atc_step_id']
            isOneToOne: false
            referencedRelation: 'atc_steps'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'run_steps_run_atc_id_fkey'
            columns: ['run_atc_id']
            isOneToOne: false
            referencedRelation: 'run_atcs'
            referencedColumns: ['id']
          },
        ]
      }
      runs: {
        Row: {
          abort_reason: string | null
          created_at: string
          environment_id: string
          executor_mode: string
          executor_user_id: string | null
          finished_at: string | null
          id: string
          module_id: string | null
          project_id: string
          start_token: string
          started_at: string
          status: string
          test_id: string
          test_title: string
          updated_at: string
          version: number
          workspace_id: string
        }
        Insert: {
          abort_reason?: string | null
          created_at?: string
          environment_id: string
          executor_mode: string
          executor_user_id?: string | null
          finished_at?: string | null
          id?: string
          module_id?: string | null
          project_id: string
          start_token: string
          started_at?: string
          status?: string
          test_id: string
          test_title: string
          updated_at?: string
          version?: number
          workspace_id: string
        }
        Update: {
          abort_reason?: string | null
          created_at?: string
          environment_id?: string
          executor_mode?: string
          executor_user_id?: string | null
          finished_at?: string | null
          id?: string
          module_id?: string | null
          project_id?: string
          start_token?: string
          started_at?: string
          status?: string
          test_id?: string
          test_title?: string
          updated_at?: string
          version?: number
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'runs_environment_id_fkey'
            columns: ['environment_id']
            isOneToOne: false
            referencedRelation: 'project_environments'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'runs_module_id_fkey'
            columns: ['module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'runs_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'runs_test_id_fkey'
            columns: ['test_id']
            isOneToOne: false
            referencedRelation: 'tests'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'runs_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      test_steps: {
        Row: {
          atc_id: string
          id: string
          position: number
          test_id: string
        }
        Insert: {
          atc_id: string
          id?: string
          position: number
          test_id: string
        }
        Update: {
          atc_id?: string
          id?: string
          position?: number
          test_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'test_steps_atc_id_fkey'
            columns: ['atc_id']
            isOneToOne: false
            referencedRelation: 'atcs'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'test_steps_test_id_fkey'
            columns: ['test_id']
            isOneToOne: false
            referencedRelation: 'tests'
            referencedColumns: ['id']
          },
        ]
      }
      tests: {
        Row: {
          created_at: string
          created_by: string
          id: string
          tags: string[]
          title: string
          updated_at: string
          version: number
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          id?: string
          tags?: string[]
          title: string
          updated_at?: string
          version?: number
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          tags?: string[]
          title?: string
          updated_at?: string
          version?: number
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'tests_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      user_stories: {
        Row: {
          archived_at: string | null
          created_at: string
          description: string | null
          external_id: string | null
          external_url: string | null
          id: string
          module_id: string
          project_id: string | null
          status: string
          title: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          external_id?: string | null
          external_url?: string | null
          id?: string
          module_id: string
          project_id?: string | null
          status?: string
          title: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          description?: string | null
          external_id?: string | null
          external_url?: string | null
          id?: string
          module_id?: string
          project_id?: string | null
          status?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: 'user_stories_module_id_fkey'
            columns: ['module_id']
            isOneToOne: false
            referencedRelation: 'modules'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'user_stories_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      user_view_state: {
        Row: {
          project_id: string
          state: Json
          updated_at: string
          user_id: string
          view_kind: string
        }
        Insert: {
          project_id: string
          state?: Json
          updated_at?: string
          user_id: string
          view_kind: string
        }
        Update: {
          project_id?: string
          state?: Json
          updated_at?: string
          user_id?: string
          view_kind?: string
        }
        Relationships: [
          {
            foreignKeyName: 'user_view_state_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
        ]
      }
      workspace_invite_secrets: {
        Row: {
          invite_id: string
          token_hash: string
        }
        Insert: {
          invite_id: string
          token_hash: string
        }
        Update: {
          invite_id?: string
          token_hash?: string
        }
        Relationships: [
          {
            foreignKeyName: 'workspace_invite_secrets_invite_id_fkey'
            columns: ['invite_id']
            isOneToOne: true
            referencedRelation: 'workspace_invites'
            referencedColumns: ['id']
          },
        ]
      }
      workspace_invites: {
        Row: {
          accepted_at: string | null
          accepted_by_user_id: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by_user_id: string | null
          revoked_at: string | null
          role: string
          workspace_id: string
        }
        Insert: {
          accepted_at?: string | null
          accepted_by_user_id?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by_user_id?: string | null
          revoked_at?: string | null
          role?: string
          workspace_id: string
        }
        Update: {
          accepted_at?: string | null
          accepted_by_user_id?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by_user_id?: string | null
          revoked_at?: string | null
          role?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'workspace_invites_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      workspace_members: {
        Row: {
          joined_at: string
          role: string
          status: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          joined_at?: string
          role?: string
          status?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          joined_at?: string
          role?: string
          status?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'workspace_members_workspace_id_fkey'
            columns: ['workspace_id']
            isOneToOne: false
            referencedRelation: 'workspaces'
            referencedColumns: ['id']
          },
        ]
      }
      workspaces: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_user_id: string
          plan: string
          slug: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          owner_user_id: string
          plan?: string
          slug: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_user_id?: string
          plan?: string
          slug?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      auth_email_status: {
        Args: { p_email: string }
        Returns: {
          email_confirmed: boolean
          email_exists: boolean
        }[]
      }
      bunkai_abort_run: {
        Args: { p_actor_user_id: string, p_reason: string, p_run_id: string }
        Returns: Json
      }
      bunkai_archive_acceptance_criterion: {
        Args: { p_id: string }
        Returns: Json
      }
      bunkai_archive_module_subtree: {
        Args: { p_module_id: string }
        Returns: Json
      }
      bunkai_assert_actor_can_read_workspace: {
        Args: { p_actor_user_id: string, p_workspace_id: string }
        Returns: undefined
      }
      bunkai_assert_actor_can_write_project: {
        Args: { p_actor_user_id: string, p_project_id: string }
        Returns: string
      }
      bunkai_assert_actor_can_write_workspace: {
        Args: { p_actor_user_id: string, p_workspace_id: string }
        Returns: undefined
      }
      bunkai_atc_json: { Args: { p_atc_id: string }, Returns: Json }
      bunkai_atc_usage: {
        Args: { p_actor_user_id: string, p_atc_id: string }
        Returns: Json
      }
      bunkai_bootstrap_workspace: {
        Args: { p_name: string, p_slug: string }
        Returns: string
      }
      bunkai_bug_json: { Args: { p_bug_id: string }, Returns: Json }
      bunkai_can_write_workspace: { Args: { ws_id: string }, Returns: boolean }
      bunkai_create_atc: {
        Args: {
          p_ac_ids: string[]
          p_actor_user_id: string
          p_assertions: Json
          p_layer: string
          p_module_id: string
          p_steps: Json
          p_tags: string[]
          p_title: string
          p_user_story_id: string
        }
        Returns: Json
      }
      bunkai_create_bug: {
        Args: {
          p_actor_user_id: string
          p_atc_id: string
          p_description: string
          p_evidence_urls: string[]
          p_module_id: string
          p_project_id: string
          p_run_id: string
          p_run_step_id: string
          p_severity: string
          p_steps_to_reproduce: string
          p_title: string
        }
        Returns: Json
      }
      bunkai_create_environment: {
        Args: { p_actor_user_id: string, p_name: string, p_project_id: string }
        Returns: Json
      }
      bunkai_create_run: {
        Args: {
          p_actor_user_id: string
          p_environment_id: string
          p_executor_mode: string
          p_start_token: string
          p_test_id: string
        }
        Returns: Json
      }
      bunkai_create_test: {
        Args: {
          p_actor_user_id: string
          p_atc_ids: string[]
          p_title: string
          p_workspace_id: string
        }
        Returns: Json
      }
      bunkai_delete_environment: {
        Args: { p_actor_user_id: string, p_environment_id: string }
        Returns: Json
      }
      bunkai_duplicate_atc: {
        Args: {
          p_actor_user_id: string
          p_source_atc_id: string
          p_title?: string
        }
        Returns: Json
      }
      bunkai_filter_tests_by_tag: {
        Args: { p_actor_user_id: string, p_tag: string }
        Returns: Json
      }
      bunkai_finish_run: {
        Args: { p_actor_user_id: string, p_run_id: string, p_verdict: string }
        Returns: Json
      }
      bunkai_get_atc: {
        Args: { p_actor_user_id: string, p_atc_id: string }
        Returns: Json
      }
      bunkai_get_run_expanded: {
        Args: { p_actor_user_id: string, p_run_id: string }
        Returns: Json
      }
      bunkai_get_test_expanded: {
        Args: { p_actor_user_id: string, p_test_id: string }
        Returns: Json
      }
      bunkai_insert_acceptance_criterion: {
        Args: {
          p_description?: string
          p_position?: number
          p_title: string
          p_user_story_id: string
        }
        Returns: Json
      }
      bunkai_is_workspace_admin: { Args: { ws_id: string }, Returns: boolean }
      bunkai_is_workspace_member: { Args: { ws_id: string }, Returns: boolean }
      bunkai_is_workspace_owner: { Args: { ws_id: string }, Returns: boolean }
      bunkai_leave_workspace: {
        Args: { p_workspace_id: string }
        Returns: undefined
      }
      bunkai_list_activity: {
        Args: {
          p_actions?: string[]
          p_cursor_created_at?: string
          p_cursor_id?: string
          p_limit?: number
          p_workspace_id: string
        }
        Returns: Json
      }
      bunkai_list_project_bugs: {
        Args: { p_actor_user_id: string, p_project_id: string }
        Returns: Json
      }
      bunkai_list_test_runs: {
        Args: {
          p_actor_user_id: string
          p_cursor_id?: string
          p_cursor_started_at?: string
          p_limit?: number
          p_outcome?: string
          p_test_id: string
        }
        Returns: Json
      }
      bunkai_mark_run_step: {
        Args: {
          p_actor_user_id: string
          p_evidence_url: string
          p_note: string
          p_run_id: string
          p_run_step_id: string
          p_status: string
        }
        Returns: Json
      }
      bunkai_move_acceptance_criterion: {
        Args: { p_id: string, p_new_position: number }
        Returns: Json
      }
      bunkai_move_module: {
        Args: { p_module_id: string, p_new_parent_id?: string }
        Returns: Json
      }
      bunkai_normalize_test_tags: {
        Args: { p_tags: string[] }
        Returns: string[]
      }
      bunkai_rename_environment: {
        Args: {
          p_actor_user_id: string
          p_environment_id: string
          p_name: string
        }
        Returns: Json
      }
      bunkai_reorder_test_steps: {
        Args: {
          p_actor_user_id: string
          p_if_match: number
          p_step_ids: string[]
          p_test_id: string
        }
        Returns: Json
      }
      bunkai_report_project_coverage: {
        Args: { p_actor_user_id: string, p_project_id: string }
        Returns: Json
      }
      bunkai_report_project_runs: {
        Args: {
          p_actor_user_id: string
          p_cursor_id?: string
          p_cursor_started_at?: string
          p_date_from?: string
          p_date_to?: string
          p_executor_mode?: string[]
          p_limit?: number
          p_module_id?: string
          p_project_id: string
          p_status?: string[]
        }
        Returns: Json
      }
      bunkai_resolve_activity_actors: {
        Args: { p_user_ids: string[], p_workspace_id: string }
        Returns: {
          email: string
          user_id: string
        }[]
      }
      bunkai_run_json: { Args: { p_run_id: string }, Returns: Json }
      bunkai_save_atc: {
        Args: {
          p_ac_ids: string[]
          p_assertions: Json
          p_atc_id: string
          p_layer: string
          p_steps: Json
          p_tags: string[]
          p_title: string
          p_user_story_id: string
        }
        Returns: undefined
      }
      bunkai_search_atcs: {
        Args: {
          p_actor_user_id: string
          p_layer?: string
          p_limit?: number
          p_module_id?: string
          p_project_id: string
          p_query: string
        }
        Returns: Json
      }
      bunkai_set_test_tags: {
        Args: {
          p_actor_user_id: string
          p_if_match: number
          p_tags: string[]
          p_test_id: string
        }
        Returns: Json
      }
      bunkai_set_user_story_status: {
        Args: { p_id: string, p_status: string }
        Returns: Json
      }
      bunkai_test_json: { Args: { p_test_id: string }, Returns: Json }
      bunkai_test_tags_shape_ok: {
        Args: { p_tags: string[] }
        Returns: boolean
      }
      bunkai_update_atc: {
        Args: {
          p_ac_ids: string[]
          p_actor_user_id: string
          p_assertions: Json
          p_atc_id: string
          p_if_match: number
          p_layer: string
          p_steps: Json
          p_tags: string[]
          p_title: string
        }
        Returns: Json
      }
      bunkai_update_module: {
        Args: {
          p_description?: string
          p_module_id: string
          p_name?: string
          p_new_slug?: string
          p_update_description?: boolean
        }
        Returns: Json
      }
      bunkai_user_id_by_email: { Args: { p_email: string }, Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
  | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
      & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
      ? R
      : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables']
    & DefaultSchema['Views'])
    ? (DefaultSchema['Tables']
      & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
        ? R
        : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema['Tables']
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
    Insert: infer I
  }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema['Tables']
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
    Update: infer U
  }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
  | keyof DefaultSchema['Enums']
  | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
  | keyof DefaultSchema['CompositeTypes']
  | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
