#!/usr/bin/env bun
/**
 * Regenerates `lib/types/supabase.ts` from the live Supabase schema.
 *
 * Modes:
 *   - default (CLI): `bunx supabase gen types typescript --project-id <ref> --schema public`.
 *                    Note: `--schema auth` is intentionally omitted to keep the
 *                    output byte-identical to the original MCP-generated file
 *                    (Phase D / E.3 baseline). No app code references
 *                    `Database['auth']` directly, so adding the schema would
 *                    only bloat the type without enabling new call sites.
 *   - `--mcp`      : documented contract — MCP regeneration must run inside a
 *                    Claude Code session via `mcp__claude_ai_Supabase__generate_typescript_types`,
 *                    not from a standalone Bun script. This flag exits 1 with a
 *                    pointer to the CLI path so the failure mode is explicit.
 *
 * Project ref resolution order:
 *   1. `SUPABASE_PROJECT_REF` (explicit override).
 *   2. Derived from `NEXT_PUBLIC_SUPABASE_URL` (`https://<ref>.supabase.co`).
 *
 * Idempotency contract:
 *   When the schema has not changed, re-running this script MUST leave
 *   `lib/types/supabase.ts` byte-identical to the committed copy. The lint:fix
 *   pass at the end is what normalises the antfu/ESLint reshape that the raw
 *   CLI output otherwise drifts on (Phase D bug log entry #5).
 */

import { renameSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const REPO_ROOT = resolve(import.meta.dir, '..');
const TARGET = resolve(REPO_ROOT, 'lib/types/supabase.ts');
const TMP = `${TARGET}.tmp`;
const CLI_TIMEOUT_MS = 60_000;

function fail(message: string): never {
  console.error(`✗ ${message}`);
  process.exit(1);
}

function resolveProjectRef(): string {
  const explicit = process.env.SUPABASE_PROJECT_REF?.trim();
  if (explicit) {
    return explicit;
  }
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  if (!url) {
    fail(
      'Cannot resolve Supabase project ref. Set SUPABASE_PROJECT_REF or NEXT_PUBLIC_SUPABASE_URL in .env (see .env.example).',
    );
  }
  const match = url.match(/^https:\/\/([a-z0-9]+)\.supabase\.co/i);
  if (!match) {
    fail(
      `NEXT_PUBLIC_SUPABASE_URL does not match the expected shape https://<ref>.supabase.co (got: ${url}).`,
    );
  }
  return match[1];
}

async function ensureSupabaseCli(): Promise<void> {
  const proc = Bun.spawn(['bunx', 'supabase', '--version'], {
    cwd: REPO_ROOT,
    stdout: 'pipe',
    stderr: 'pipe',
  });
  const exit = await proc.exited;
  if (exit !== 0) {
    fail(
      'Supabase CLI not available. Install it: https://supabase.com/docs/guides/cli. '
      + 'The `--mcp` mode is a documented stub — MCP regeneration must run inside a Claude Code session.',
    );
  }
}

async function runCli(projectRef: string): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), CLI_TIMEOUT_MS);
  try {
    const proc = Bun.spawn(
      [
        'bunx',
        'supabase',
        'gen',
        'types',
        'typescript',
        '--project-id',
        projectRef,
        '--schema',
        'public',
      ],
      {
        cwd: REPO_ROOT,
        stdout: 'pipe',
        stderr: 'pipe',
        signal: controller.signal,
      },
    );
    const [stdout, stderr, exit] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ]);
    if (exit !== 0) {
      fail(`Supabase CLI exited ${exit}.\n${stderr.trim()}`);
    }
    if (!stdout.trim()) {
      fail(`Supabase CLI produced empty output.\n${stderr.trim()}`);
    }
    return stdout;
  }
  catch (err) {
    if (err instanceof Error && err.name === 'AbortError') {
      fail(`Supabase CLI timed out after ${CLI_TIMEOUT_MS / 1000}s.`);
    }
    throw err;
  }
  finally {
    clearTimeout(timeout);
  }
}

async function lintFix(): Promise<void> {
  const proc = Bun.spawn(['bun', 'run', 'lint:fix', TARGET], {
    cwd: REPO_ROOT,
    stdout: 'pipe',
    stderr: 'pipe',
  });
  const [stdout, stderr, exit] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (exit !== 0) {
    fail(`lint:fix failed (exit ${exit}).\nstdout:\n${stdout.trim()}\nstderr:\n${stderr.trim()}`);
  }
}

function preserveHeader(generated: string): string {
  // The committed file carries a human-authored provenance header. Re-apply it
  // so the diff stays clean across regenerations. The CLI output starts with
  // its own banner; we replace it wholesale.
  const header = [
    '// Generated by `mcp__claude_ai_Supabase__generate_typescript_types` against',
    '// project fmbpikzpkafptqximhxn. Do not edit by hand — regenerate after any',
    '// migration applied to the Bunkai Supabase project, then `bun run lint:fix`',
    '// to apply the codebase\'s antfu/ESLint style conventions.',
    '',
    '',
  ].join('\n');
  const stripped = generated.replace(/^(?:\s*\/\/[^\n]*\n)+/, '');
  return header + stripped;
}

async function main(): Promise<void> {
  if (process.argv.includes('--mcp')) {
    console.error(
      'MCP mode must run inside a Claude Code session; use `bun run types:gen` for CLI.',
    );
    process.exit(1);
  }

  const projectRef = resolveProjectRef();
  await ensureSupabaseCli();

  const raw = await runCli(projectRef);
  const withHeader = preserveHeader(raw);

  writeFileSync(TMP, withHeader, 'utf8');
  try {
    renameSync(TMP, TARGET);
  }
  catch (err) {
    try {
      unlinkSync(TMP);
    }
    catch {}
    throw err;
  }

  await lintFix();

  const bytes = statSync(TARGET).size;
  console.log(`✓ Regenerated lib/types/supabase.ts (${bytes} bytes) for project ${projectRef}`);
}

await main();
